# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.1"
manifest_format = "2.0"
project_hash = "9257328fa82e5752bad0116b6a9f1a2e00c29a82"

[[deps.Ionic]]
path = "."
uuid = "1fe31619-e050-4c22-88e3-621fdf7467f4"
version = "0.1.0"
