name = "Ionic"
uuid = "1fe31619-e050-4c22-88e3-621fdf7467f4"
version = "0.1.0"
authors = ["ken-morel <engonken8@gmail.com>"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
Dates = "1.11.0"
Test = "1.11.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
